#!/usr/bin/env python3
"""Generates src/unicode_alphabetic_table.h from the Unicode Character
Database DerivedCoreProperties.txt (property: Alphabetic).

Usage: scripts/gen_unicode_alphabetic.py [path or URL]
Without an argument, downloads Unicode 16.0.0 from unicode.org.
"""

import re
import sys
import urllib.request

UCD_URL = "https://www.unicode.org/Public/16.0.0/ucd/DerivedCoreProperties.txt"
OUT_PATH = "src/unicode_alphabetic_table.h"

HEADER = """\
/**
 * Generated by scripts/gen_unicode_alphabetic.py from Unicode {version}
 * DerivedCoreProperties.txt (property: Alphabetic). Do not edit by hand.
 *
 * Sorted, non-overlapping inclusive [lo, hi] codepoint ranges; binary
 * searched by unicode_alphabetic.
 */
#ifndef LONG_UNICODE_ALPHABETIC_TABLE_H
#define LONG_UNICODE_ALPHABETIC_TABLE_H

#include <stdint.h>
#include <stdbool.h>

static const uint32_t alphabetic_ranges[][2] = {
"""

FOOTER = """\
};

static inline bool unicode_alphabetic(uint32_t c)
{
    if (c < 0x80)
        return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z');

    int64_t lo = 0;
    int64_t hi = (int64_t)(sizeof(alphabetic_ranges) / sizeof(alphabetic_ranges[0]));
    while (lo < hi) {
        int64_t mid = lo + (hi - lo) / 2;
        if (c < alphabetic_ranges[mid][0])
            hi = mid;
        else if (c > alphabetic_ranges[mid][1])
            lo = mid + 1;
        else
            return true;
    }
    return false;
}

#endif
"""


def read_source(arg):
    if arg is None:
        arg = UCD_URL
    if arg.startswith("http://") or arg.startswith("https://"):
        with urllib.request.urlopen(arg) as response:
            return response.read().decode()
    with open(arg) as f:
        return f.read()


def parse_version(text):
    m = re.search(r"DerivedCoreProperties-([0-9.]+)\.txt", text)
    return m.group(1) if m else "unknown"


def parse_ranges(text):
    line_re = re.compile(
        r"^([0-9A-F]{4,6})(?:\.\.([0-9A-F]{4,6}))?\s*;\s*Alphabetic\s*[#;]"
    )
    ranges = []
    for line in text.splitlines():
        m = line_re.match(line)
        if m is None:
            continue
        lo = int(m.group(1), 16)
        hi = int(m.group(2), 16) if m.group(2) else lo
        ranges.append((lo, hi))

    ranges.sort()
    merged = []
    for lo, hi in ranges:
        if merged and lo <= merged[-1][1] + 1:
            merged[-1][1] = max(merged[-1][1], hi)
        else:
            merged.append([lo, hi])
    return merged


def emit(version, ranges):
    rows = [f"{{ 0x{lo:04X}, 0x{hi:04X} }}," for lo, hi in ranges]
    width = max(len(row) for row in rows) + 1
    lines = []
    for i in range(0, len(rows), 4):
        chunk = "".join(row.ljust(width) for row in rows[i : i + 4])
        lines.append("    " + chunk.rstrip())
    return HEADER.replace("{version}", version) + "\n".join(lines) + "\n" + FOOTER


def main():
    arg = sys.argv[1] if len(sys.argv) > 1 else None
    text = read_source(arg)
    ranges = parse_ranges(text)
    if not ranges:
        sys.exit("no Alphabetic ranges found in input")
    with open(OUT_PATH, "w") as f:
        f.write(emit(parse_version(text), ranges))
    print(f"{OUT_PATH}: {len(ranges)} ranges")


if __name__ == "__main__":
    main()
